// <auto-generated />
namespace Casgem_CodeFirstProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_tableSecondBlog_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_tableSecondBlog_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202307221030231_mig_tableSecondBlog_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
